<?php

namespace AP\EsoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoriesRepository extends EntityRepository
{
}
